### ISSUE TITLE
Notifciation Email Not Received When new Publisher Account Created on Staging Registry

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#85]
A publisher recently created a new account on the staging Registry account at  https://iati-staging.ckan.io. However, we did not appear to receive an email notification to let us know that the account had been created. This is essential for us as we need to 'authorise' the account (ie amend the status from 'Pending' to 'Active' so the publisher can add datasets to the account) and there is also (as far as I am aware?) no other way that we are able to view accounts that are 'Pending' unless we no the Publisher ID that they have been created with.

Also, as our users will be creating accounts on the staging site to test out their own applications we need this functionality to be reinstated ASAP. TIA

**Comment by dalepotter** [comment]
To confirm the clarification sought by @peppe1337 , we want to receive an email notification after a user registers. This happens on our [current live portal](https://iatiregistry.org/) (running CKAN v2.1.4), but not on the [new staging version](https://iati-staging.ckan.io/) (running CKAN v.2.5.2).

**Comment by dalepotter** [comment]
Following a recent call with @chrisviderum we understand that this issue is almost resolved.

**Comment by chrisviderum** [comment]
@dalepotter @wendyrogers 

This issue should be resolved. The iati-staging portal was updated with a fix.

**Comment by dalepotter** [comment]
Thanks for this update @chrisviderum 

@wendyrogers would you be able to test this feature on the [new iati-staging portal](https://iati-staging.ckan.io)?

**Comment by wendyrogers** [comment]
@dalepotter  Yes have tested by creating a new publisher account but did still not receive an email notification? NB notification should go to the same set of Admins as for the live Registry

@chrisviderum - please can you check fix? Thanks

**Comment by chrisviderum** [comment]
@wendyrogers thanks for the update. Can you tell me which publisher account you have created? We will investigate on this one.

**Comment by wendyrogers** [comment]
@chrisviderum I couldn't find the original publisher account I created but have therefore created another https://iati-staging.ckan.io/publisher/wrtest with the same issue.

Also, is there currently any way to view all accounts with a status of 'Pending' via the user interface?

**Comment by chrisviderum** [comment]
@wendyrogers thanks! We will investigate.

This is a good question, but I don't think so.

**Comment by chrisviderum** [comment]
@wendyrogers we added admin accounts now. Can you maybe try it again?

**Comment by wendyrogers** [comment]
Thanks @chrisviderum have retested and have now received a notification email as required. Please can you make sure that the Admin account are retained / recreated each time the staging site is updated. Many thanks

**Comment by chrisviderum** [comment]
@wendyrogers great news! We will do from now on. The next time we update the database is on Tuesday, the 27th of September. Correct @dalepotter ?

**Comment by chrisviderum** [comment]
@wendyrogers we updated the database yesterday. Would you like to do an additional to test and check, if it working like it should?

**Comment by wendyrogers** [comment]
Thanks @chrisviderum have retested and email received as required.

**Comment by chrisviderum** [comment]
@wendyrogers are all notifiactions received as planned?

**Comment by wendyrogers** [comment]
@chrisviderum yes we are receiving the new account notification but they currently contain the 'wrong' registry account URL. eg the emails reference  https://iatiregistry.ckan.io/publisher/soundseekers rather than https://www.iatiregistry.org/publisher soundseekers Although cosmetic please could the email text be amended to use the www.iatiregistry.org domain

**Comment by rory09** [comment]
@wendyrogers, @chrisviderum I think this is a broader problem that the `.io` address is still set as the site address. This means that all of the API responses which return a link to the registry will return the `.io` address, not `iatiregistry.org` - this isn't a huge issue right now, but if you were to stop serving on the the `.io` address, things could get very messy.

See here for what I'm talking about: https://iatiregistry.org/api/3/action/status_show 

The response is this:

```json
{

    "help": "https://iatiregistry.ckan.io/api/3/action/help_show?name=status_show",
    "success": true,
    "result": {
        "ckan_version": "2.5.2",
        "site_url": "https://iatiregistry.ckan.io",
        "site_description": "",
        "site_title": "IATI Registry",
        "error_emails_to": null,
        "locale_default": "en",
        "extensions": [
            "image_view",
            "text_view",
            "recline_view",
            "datapusher",
            "envvars",
            "iati_publishers",
            "iati_datasets",
            "iati_theme",
            "iati_csv",
            "sentry"
        ]
    }

}
```

Hopefully this shouldn't take long to change?

**Comment by klikstermkd** [comment]
Just to be clear. The issue here is that if a user register a new publisher through ``iatiregistry.org``, the URL that's in the email points to ``iatiregistry.ckan.io``, right?

**Comment by wendyrogers** [comment]
This issue was originally raised because the URL received in the notification emails contained the site URL https://iatiregistry.ckan.io rather than https://www.iatiregistry.org. However, re Rory's post above is this because the site address is still set to https://iatiregistry.ckan.io rathe than https://www.iatiregistry.org ? If this is the case then it would be better to amend the site address rather than just making a cosmetic change to the notification email?

**Comment by chrisviderum** [comment]
@wendyrogers @rory09 

Can you run a test, if it's working now?

**Comment by rory09** [comment]
Hi Chris - it appears to be working now, thank you.

Best,
Rory

**Comment by wendyrogers** [comment]
Yes latest emails received have URLs that include https://www.iatiregistry.org rather than https://iatiregistry.ckan.io. Thanks

**Comment by dalepotter** [comment]
A fix for this issue has been deployed to the live instance of the IATI Registry. Therefore this issue is being closed.
